package repository

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"webtag/internal/alloc"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/pgvector/pgvector-go"

	"webtag/internal/concept"
)

// GetConceptIDByAlias is the resolver's fast path. The lookup is case
// insensitive because aliases were stored lower-cased by UpsertAlias.
// Returns (uuid.Nil, false, nil) when no alias matches — distinguishes
// a clean miss from a SQL error.
func (r *PGXConceptRepository) GetConceptIDByAlias(ctx context.Context, alias string) (uuid.UUID, bool, error) {
	alias = strings.ToLower(strings.TrimSpace(alias))
	if alias == "" {
		return uuid.Nil, false, nil
	}
	var id uuid.UUID
	err := r.db.QueryRow(ctx,
		`SELECT concept_id FROM concept_alias WHERE alias = $1`,
		alias,
	).Scan(&id)
	if errors.Is(err, pgx.ErrNoRows) {
		return uuid.Nil, false, nil
	}
	if err != nil {
		return uuid.Nil, false, fmt.Errorf("concept alias lookup %q: %w", alias, err)
	}
	return id, true, nil
}

// GetConceptIDByQID maps a Wikidata QID to a local concept. The v3
// resolver no longer anchors on Wikidata, but the wikidata_qid column
// and this lookup are retained so legacy QID-anchored rows stay
// addressable (and the unique-QID race recovery in CreateConcept can
// still re-read by QID if a caller ever supplies one).
func (r *PGXConceptRepository) GetConceptIDByQID(ctx context.Context, qid string) (uuid.UUID, bool, error) {
	qid = strings.TrimSpace(qid)
	if qid == "" {
		return uuid.Nil, false, nil
	}
	var id uuid.UUID
	err := r.db.QueryRow(ctx,
		`SELECT id FROM concept WHERE wikidata_qid = $1`,
		qid,
	).Scan(&id)
	if errors.Is(err, pgx.ErrNoRows) {
		return uuid.Nil, false, nil
	}
	if err != nil {
		return uuid.Nil, false, fmt.Errorf("concept qid lookup %q: %w", qid, err)
	}
	return id, true, nil
}

// CreateConcept inserts a row in `concept` together with its identity alias
// and returns the canonical ID.
// Empty WikidataQID is stored as NULL so the unique index permits
// many concepts. The (uuid generated by DB default) is returned via
// RETURNING so the resolver can immediately use it for alias inserts in
// the same call sequence.
//
// Embedding / EmbeddingModel are written together when the v3 vector
// gate admits a concept with a fresh vector: both present → the row is
// immediately a nearest-neighbour comparison target. Empty embedding
// (or empty model) leaves both columns NULL, the local-only fallback
// path the Phase 8 backfill task later fills in. The two columns move
// in lockstep — a vector without its model name is unusable for the
// model-scoped nearest-neighbour query, so we only write the pair.
//
// The concept row and identity alias share one transaction. The alias is
// globally unique in a single installation; if another writer wins that
// alias first, this transaction is rolled back and the winner's concept ID is
// returned. This makes concurrent admission converge without leaving an
// alias-less concept behind.
func (r *PGXConceptRepository) CreateConcept(ctx context.Context, params concept.CreateConceptParams) (uuid.UUID, error) {
	primary := strings.TrimSpace(params.PrimaryName)
	if primary == "" {
		return uuid.Nil, fmt.Errorf("create concept: empty primary_name")
	}
	var qidArg any
	if q := strings.TrimSpace(params.WikidataQID); q != "" {
		qidArg = q
	}

	var embeddingArg, modelArg any
	if model := strings.TrimSpace(params.EmbeddingModel); model != "" && len(params.Embedding) > 0 {
		embeddingArg = pgvector.NewVector(params.Embedding)
		modelArg = model
	}

	tx, err := r.tx.Begin(ctx)
	if err != nil {
		return uuid.Nil, fmt.Errorf("create concept %q: begin tx: %w", primary, err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	var id uuid.UUID
	err = tx.QueryRow(ctx,
		`INSERT INTO concept (primary_name, wikidata_qid, embedding, embedding_model)
		 VALUES ($1, $2, $3, $4) RETURNING id`,
		primary, qidArg, embeddingArg, modelArg,
	).Scan(&id)
	if err != nil {
		return uuid.Nil, fmt.Errorf("create concept %q: %w", primary, err)
	}

	alias := strings.ToLower(primary)
	tag, err := tx.Exec(ctx,
		`INSERT INTO concept_alias (alias, concept_id, source, confidence)
		 VALUES ($1, $2, $3, 1.0)
		 ON CONFLICT (alias) DO NOTHING`,
		alias, id, concept.SourceIdentity,
	)
	if err != nil {
		return uuid.Nil, fmt.Errorf("create concept %q identity alias: %w", primary, err)
	}
	if tag.RowsAffected() == 0 {
		if err := tx.Rollback(ctx); err != nil && !errors.Is(err, pgx.ErrTxClosed) {
			return uuid.Nil, fmt.Errorf("create concept %q alias conflict rollback: %w", primary, err)
		}
		var existing uuid.UUID
		if err := r.db.QueryRow(ctx,
			`SELECT concept_id FROM concept_alias WHERE alias = $1`,
			alias,
		).Scan(&existing); err != nil {
			return uuid.Nil, fmt.Errorf("create concept %q resolve alias conflict: %w", primary, err)
		}
		return existing, nil
	}
	if err := tx.Commit(ctx); err != nil {
		return uuid.Nil, fmt.Errorf("create concept %q: commit: %w", primary, err)
	}
	return id, nil
}

// FindNearestConcept returns the single closest concept by cosine
// distance, restricted to rows that carry a vector for the CURRENT
// embedding model. The pgvector `<=>` operator is the cosine DISTANCE
// (0 = identical direction, 2 = opposite); we convert to similarity as
// `1 - distance` in SQL and return that so the resolver compares it
// directly against the CONCEPT_* cosine thresholds.
//
// embedding_model = $2 is the staleness guard: a vector embedded by a
// different model lives in an incompatible space, so comparing across
// models would yield meaningless distances. found is false when no row
// matches the model filter (cold table / first concept of this model).
func (r *PGXConceptRepository) FindNearestConcept(ctx context.Context, embedding []float32, embeddingModel string) (concept.NearestConcept, error) {
	embeddingModel = strings.TrimSpace(embeddingModel)
	if len(embedding) == 0 || embeddingModel == "" {
		return concept.NearestConcept{}, nil
	}
	var (
		id  uuid.UUID
		sim float64
	)
	err := r.db.QueryRow(ctx,
		`SELECT id, 1 - (embedding <=> $1) AS similarity
		 FROM concept
		 WHERE embedding IS NOT NULL AND embedding_model = $2
		 ORDER BY embedding <=> $1
		 LIMIT 1`,
		pgvector.NewVector(embedding), embeddingModel,
	).Scan(&id, &sim)
	if errors.Is(err, pgx.ErrNoRows) {
		return concept.NearestConcept{}, nil
	}
	if err != nil {
		return concept.NearestConcept{}, fmt.Errorf("find nearest concept: %w", err)
	}
	return concept.NearestConcept{ConceptID: id, Similarity: sim, Found: true}, nil
}

// CountConcepts returns the total number of rows in the concept table.
// The v3 retrieve-then-select cold-start switch compares this against
// CONCEPT_COLD_START_MIN: below the threshold the parse pipeline keeps
// the legacy free-generation prompt (the词表 is too thin for candidate
// recall to be useful). The pipeline caches the result for 60s so this
// COUNT(*) fires at most once a minute regardless of parse throughput.
func (r *PGXConceptRepository) CountConcepts(ctx context.Context) (int, error) {
	var n int
	if err := r.db.QueryRow(ctx,
		`SELECT count(*) FROM concept`,
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("count concepts: %w", err)
	}
	return n, nil
}

// ListNearestConcepts powers the v3 retrieve-then-select tagging path:
// it recalls the topK concepts whose embedding is closest (cosine) to a
// content vector, restricted to the CURRENT embedding model, and returns
// each candidate's id + UI-facing name (COALESCE(display_name,
// primary_name)) in nearest-first order.
//
// embedding_model = $2 is the same staleness guard FindNearestConcept
// uses: vectors embedded by a different model live in an incompatible
// space, so only same-model rows are eligible candidates. An empty result
// (cold table / no vectors for this model yet) is returned as an empty
// slice, NOT an error — the pipeline treats "no candidates" as a signal to
// fall back to free-generation tagging.
//
// topK is clamped to a sane lower bound of 1 so a misconfigured zero/
// negative value does not turn the query into a degenerate LIMIT 0.
func (r *PGXConceptRepository) ListNearestConcepts(ctx context.Context, embedding []float32, embeddingModel string, topK int) ([]concept.CandidateConcept, error) {
	embeddingModel = strings.TrimSpace(embeddingModel)
	if len(embedding) == 0 || embeddingModel == "" {
		return nil, nil
	}
	if topK < 1 {
		topK = 1
	}
	rows, err := r.db.Query(ctx,
		`SELECT id, COALESCE(display_name, primary_name) AS name
		 FROM concept
		 WHERE embedding IS NOT NULL AND embedding_model = $2
		 ORDER BY embedding <=> $1
		 LIMIT $3`,
		pgvector.NewVector(embedding), embeddingModel, topK,
	)
	if err != nil {
		return nil, fmt.Errorf("list nearest concepts: %w", err)
	}
	defer rows.Close()

	out := make([]concept.CandidateConcept, 0, alloc.Hint(topK))
	for rows.Next() {
		var c concept.CandidateConcept
		if err := rows.Scan(&c.ConceptID, &c.Name); err != nil {
			return nil, fmt.Errorf("scan nearest concept row: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate nearest concept rows: %w", err)
	}
	return out, nil
}

// neighbourMaxCosineDistance is the similarity floor for a link to count as
// a neighbour: pgvector's `<=>` is cosine DISTANCE, so 0.25 means cosine
// similarity ≥ 0.75.
//
// The direct leg has no floor and does not need one — it measures
// content↔concept similarity directly, so a weak match is merely a weak
// candidate. The co-occurrence leg is two hops (content → link → concept), so
// an unrelated neighbour contributes concepts with no relationship to the
// content at all. Without a floor, `ORDER BY … LIMIT 10` always returns ten
// links however far away they are — and just after CONCEPT_COLD_START_MIN,
// when the corpus is thin, "the ten nearest" can mean "ten arbitrary links".
//
// Injecting those is worse than injecting nothing: retrieveTagInstructions
// tells the model to copy candidates verbatim and allows at most one new tag,
// so noisy candidates actively pull it away from coining the right one.
// 0.75 matches the threshold karakeep applies to the same content→neighbour→
// tags recall.
const neighbourMaxCosineDistance = 0.25

// ListConceptsOfNearestLinks is the co-occurrence leg of candidate recall:
// it walks content → nearest already-parsed links → the concepts those links
// carry, and ranks the result by how many of the neighbours share each
// concept. A concept on 5 of 10 neighbours is a far stronger suggestion than
// one seen on a single link, so freq DESC is the ordering that matters; name
// is the tiebreak purely to keep the output deterministic.
//
// This recalls concepts the content's own vector cannot reach —
// ListNearestConcepts can only surface a concept whose embedding sits near
// the text, which structurally misses meta concepts (a 科技周刊's body is
// about AI and chips, never about being a weekly).
//
// excludeLinkID drops the link being parsed. It matters on re-parse: by then
// the link already has an embedding and its own link_concept rows, so it
// would be its own nearest neighbour and vote for the exact tag set we are
// trying to recompute. Pass uuid.Nil for a first parse.
func (r *PGXConceptRepository) ListConceptsOfNearestLinks(
	ctx context.Context,
	embedding []float32,
	embeddingModel string,
	linkTopK, conceptLimit int,
	excludeLinkID uuid.UUID,
) ([]concept.CandidateConcept, error) {
	embeddingModel = strings.TrimSpace(embeddingModel)
	if len(embedding) == 0 || embeddingModel == "" {
		return nil, nil
	}
	if linkTopK < 1 {
		linkTopK = 1
	}
	if conceptLimit < 1 {
		conceptLimit = 1
	}
	rows, err := r.db.Query(ctx,
		`WITH nearest_links AS (
		     SELECT id
		     FROM links
		     WHERE status = 'done'
		       AND embedding IS NOT NULL
		       AND embedding_model = $2
		       AND id <> $4
		       AND embedding <=> $1 <= $6
		     ORDER BY embedding <=> $1
		     LIMIT $3
		 )
		 SELECT c.id, COALESCE(c.display_name, c.primary_name) AS name, count(*) AS freq
		 FROM link_concept lc
		 JOIN nearest_links nl ON nl.id = lc.link_id
		 JOIN concept c ON c.id = lc.concept_id
		 GROUP BY c.id
		 ORDER BY freq DESC, name
		 LIMIT $5`,
		pgvector.NewVector(embedding), embeddingModel, linkTopK, excludeLinkID, conceptLimit,
		neighbourMaxCosineDistance,
	)
	if err != nil {
		return nil, fmt.Errorf("list concepts of nearest links: %w", err)
	}
	defer rows.Close()

	out := make([]concept.CandidateConcept, 0, alloc.Hint(conceptLimit))
	for rows.Next() {
		var (
			c    concept.CandidateConcept
			freq int
		)
		if err := rows.Scan(&c.ConceptID, &c.Name, &freq); err != nil {
			return nil, fmt.Errorf("scan neighbour concept row: %w", err)
		}
		out = append(out, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate neighbour concept rows: %w", err)
	}
	return out, nil
}

// UpsertAlias inserts a globally unique alias. Re-resolving the same alias
// against the same concept is idempotent; trying to assign it to a different
// concept returns a conflict so the resolver can re-read the authoritative
// owner. Aliases are stored lower-cased so lookup uses simple equality.
func (r *PGXConceptRepository) UpsertAlias(ctx context.Context, params concept.UpsertAliasParams) error {
	alias := strings.ToLower(strings.TrimSpace(params.Alias))
	if alias == "" {
		return fmt.Errorf("upsert alias: empty alias")
	}
	if params.ConceptID == uuid.Nil {
		return fmt.Errorf("upsert alias: nil concept_id")
	}
	var langArg any
	if l := strings.TrimSpace(params.Lang); l != "" {
		langArg = l
	}
	tag, err := r.db.Exec(ctx,
		`INSERT INTO concept_alias (alias, concept_id, lang, source, confidence)
		 VALUES ($1, $2, $3, $4, $5)
		 ON CONFLICT (alias) DO NOTHING`,
		alias, params.ConceptID, langArg, params.Source, params.Confidence,
	)
	if err != nil {
		return fmt.Errorf("upsert alias %q: %w", alias, err)
	}
	if tag.RowsAffected() == 0 {
		var existing uuid.UUID
		if err := r.db.QueryRow(ctx,
			`SELECT concept_id FROM concept_alias WHERE alias = $1`,
			alias,
		).Scan(&existing); err != nil {
			return fmt.Errorf("upsert alias %q conflict lookup: %w", alias, err)
		}
		if existing != params.ConceptID {
			return fmt.Errorf("upsert alias %q: already belongs to concept %s", alias, existing)
		}
	}
	return nil
}

// IncrementUseCount bumps the popularity counter for a concept. Used
// by the resolver after every successful link_concept attach so the
// UI can sort concepts by usage.
func (r *PGXConceptRepository) IncrementUseCount(ctx context.Context, conceptID uuid.UUID) error {
	_, err := r.db.Exec(ctx,
		`UPDATE concept SET use_count = use_count + 1, updated_at = now()
		 WHERE id = $1`,
		conceptID,
	)
	if err != nil {
		return fmt.Errorf("increment use_count: %w", err)
	}
	return nil
}

// AttachLinkConcept writes a (link_id, concept_id, surface_tag) row.
// Idempotent on the primary key so re-running the pipeline for the
// same link does not multiply joins. Surface tag is whatever the LLM
// produced — kept so the UI can show the user-facing wording per link.
func (r *PGXConceptRepository) AttachLinkConcept(ctx context.Context, params concept.AttachLinkConceptParams) error {
	if params.LinkID == uuid.Nil || params.ConceptID == uuid.Nil {
		return fmt.Errorf("attach link_concept: nil id")
	}
	_, err := r.db.Exec(ctx,
		`INSERT INTO link_concept (link_id, concept_id, surface_tag)
		 VALUES ($1, $2, $3)
		 ON CONFLICT (link_id, concept_id) DO NOTHING`,
		params.LinkID, params.ConceptID, strings.TrimSpace(params.SurfaceTag),
	)
	if err != nil {
		return fmt.Errorf("attach link_concept: %w", err)
	}
	return nil
}
