package dbintegration

import (
	"testing"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"webtag/internal/migrate"
)

func TestObsoleteSubsystemCleanupMigratesLegacyObjects(t *testing.T) {
	dsn := isolatedMigrationDatabase(t)
	pool := migrationTargetPool(t, dsn)
	prepareProductionUpgradeFixture(t, pool)
	installLegacyLinkClassificationSchema(t, pool)

	if _, err := pool.Exec(t.Context(), `
		CREATE TABLE public.concept (id uuid PRIMARY KEY);
		CREATE TABLE public.concept_alias (
			alias text NOT NULL,concept_id uuid NOT NULL REFERENCES public.concept(id));
		CREATE TABLE public.concept_merge_proposal (id uuid PRIMARY KEY);
		CREATE TABLE public.link_concept (
			link_id uuid NOT NULL REFERENCES public.links(id),
			concept_id uuid NOT NULL REFERENCES public.concept(id));
		CREATE TABLE public.library_classification_rules (id uuid PRIMARY KEY);
		CREATE TABLE public.library_review_items (
			id uuid PRIMARY KEY,link_id uuid REFERENCES public.links(id));
		CREATE TABLE public.reader_content_history (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			link_id uuid NOT NULL REFERENCES public.links(id));
		CREATE TABLE public.feed_lifecycle_repair_audit (
			link_id uuid NOT NULL,
			classification text NOT NULL,
			PRIMARY KEY (link_id,classification));
		CREATE TABLE public.reader_tag_activity (
			tag text PRIMARY KEY,last_at timestamptz NOT NULL,last_link_id uuid);
		CREATE TABLE public.reader_domain_activity (
			domain text PRIMARY KEY,last_at timestamptz NOT NULL,last_link_id uuid);

		ALTER TABLE public.links
			ADD COLUMN embedding text,
			ADD COLUMN embedding_model text;
		ALTER TABLE public.sites
			ADD COLUMN needs_review boolean NOT NULL DEFAULT false,
			ADD COLUMN embedding text,
			ADD COLUMN embedding_model text;
		ALTER TABLE public.site_tags ADD COLUMN concept_id uuid;

		CREATE FUNCTION public.reader_capture_content_history() RETURNS trigger
		LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
		CREATE FUNCTION public.reader_cleanup_content_history(integer,integer) RETURNS integer
		LANGUAGE sql AS $$ SELECT 0 $$;
		CREATE FUNCTION public.bump_concept_global_revision_update() RETURNS trigger
		LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$;
		CREATE FUNCTION public.bump_link_concept_read_revision_update() RETURNS trigger
		LANGUAGE plpgsql AS $$ BEGIN RETURN NULL; END $$;
		CREATE TRIGGER trg_reader_capture_content_history
		BEFORE UPDATE OF content,content_document,content_revision ON public.links
		FOR EACH ROW EXECUTE FUNCTION public.reader_capture_content_history();

		DROP TRIGGER trg_sites_representation_write_gate_upd ON public.sites;
		CREATE TRIGGER trg_sites_representation_write_gate_upd
		BEFORE UPDATE OF first_collected_at,homepage_url,icon_url,id,intro,
			last_collected_at,name,needs_review,pinned,primary_entry_id,revision,site_key,updated_at
		ON public.sites FOR EACH STATEMENT
		EXECUTE FUNCTION public.guard_representation_write_gate();

		CREATE INDEX idx_link_translations_missing_reconcile
		ON public.link_translations (updated_at,id) INCLUDE (current_river_job_id)
		WHERE status IN ('pending','processing') AND current_river_job_id IS NOT NULL;
	`); err != nil {
		t.Fatalf("create legacy obsolete subsystem objects: %v", err)
	}
	assertObsoleteSubsystemSchemaState(t, pool, 10, 14, 4)
	assertIndexExists(t, pool, "idx_link_translations_missing_reconcile", true)
	assertIndexExists(t, pool, "idx_river_job_translation_terminal_history", true)
	feedLinkID := seedLegacyClassifiedLink(t, pool, "https://cleanup.example/feed", "Feed", "body", "summary")
	feedItemID := seedReaderFeedSaveItem(t, pool, "https://cleanup.example/feed", "cleanup-feed")
	if _, err := pool.Exec(t.Context(), `
		INSERT INTO reader_feed_saves (feed_item_id,link_id,created_link) VALUES ($1,$2,true)`, feedItemID, feedLinkID); err != nil {
		t.Fatalf("seed legacy Feed save state: %v", err)
	}
	if _, err := pool.Exec(t.Context(), `
		INSERT INTO reader_feed_feedback (item_key,action) VALUES ('link:'||$1::text,'hide'),('subscription:'||$2::text,'save')`, feedLinkID, feedItemID); err != nil {
		t.Fatalf("seed legacy Feed feedback state: %v", err)
	}

	translationIDs := seedObsoleteCleanupTranslations(t, pool)

	if err := migrate.Up(t.Context(), pool); err != nil {
		t.Fatalf("apply production schema upgrade: %v", err)
	}
	assertCurrentSchemaLedger(t, pool)
	assertObsoleteSubsystemSchemaState(t, pool, 0, 0, 0)
	assertIndexExists(t, pool, "idx_link_translations_missing_reconcile", false)
	assertIndexExists(t, pool, "idx_river_job_translation_terminal_history", false)
	assertObsoleteCleanupTranslationStates(t, pool, translationIDs)
	var hides, saveColumns, retiredTranslationColumns int
	if err := pool.QueryRow(t.Context(), `SELECT count(*) FROM reader_feed_hides`).Scan(&hides); err != nil {
		t.Fatalf("count migrated Feed hides: %v", err)
	}
	if err := pool.QueryRow(t.Context(), `SELECT count(*) FROM information_schema.columns
		WHERE table_schema='public' AND ((table_name='reader_feed_hides' AND column_name='action')
			OR (table_name='reader_feed_saves' AND column_name='created_link'))`).Scan(&saveColumns); err != nil {
		t.Fatalf("inspect simplified Feed columns: %v", err)
	}
	if hides != 1 || saveColumns != 0 {
		t.Fatalf("simplified Feed state = hides:%d obsolete_columns:%d, want 1/0", hides, saveColumns)
	}
	if err := pool.QueryRow(t.Context(), `SELECT count(*) FROM information_schema.columns
		WHERE table_schema='public' AND table_name='link_translations'
			AND column_name='current_river_job_id'`).Scan(&retiredTranslationColumns); err != nil {
		t.Fatalf("inspect retired translation columns: %v", err)
	}
	if retiredTranslationColumns != 0 {
		t.Fatalf("current_river_job_id columns = %d, want 0", retiredTranslationColumns)
	}
}

type obsoleteCleanupTranslationIDs struct {
	terminal         uuid.UUID
	missing          uuid.UUID
	active           uuid.UUID
	unbound          uuid.UUID
	legacyBound      uuid.UUID
	legacyUnbound    uuid.UUID
	activeJobID      int64
	legacyRiverJobID int64
}

func seedLegacyClassifiedLink(
	t *testing.T,
	pool *pgxpool.Pool,
	rawURL, title, content, summary string,
) uuid.UUID {
	t.Helper()
	id := uuid.New()
	if _, err := pool.Exec(t.Context(), `INSERT INTO public.links (
		id,url,source_kind,source_key,input_title,input_text,title,summary,tags,status,
		content,content_document,content_format,content_source,content_revision,
		library_kind,library_kind_source,library_kind_locked,predicted_library_kind,
		classification_confidence,classifier_version,first_collected_at
	) VALUES (
		$1,$2,'browser_capture',$2,$3,$4,$3,$5,'{}','done',
		$4,$4,'markdown','user',1,
		'reading','user',false,'reading',1,'legacy-fixture',CURRENT_TIMESTAMP
	)`, id, rawURL, title, content, summary); err != nil {
		t.Fatalf("seed legacy classified Link %s: %v", rawURL, err)
	}
	return id
}

func seedObsoleteCleanupTranslations(t *testing.T, pool *pgxpool.Pool) obsoleteCleanupTranslationIDs {
	t.Helper()

	var terminalJobID int64
	if err := pool.QueryRow(t.Context(), `INSERT INTO public.river_job (
		args,kind,max_attempts,state,finalized_at
	) VALUES ('{}','translate_link_v2',3,'discarded',CURRENT_TIMESTAMP)
	RETURNING id`).Scan(&terminalJobID); err != nil {
		t.Fatalf("insert terminal translation job: %v", err)
	}
	ids := obsoleteCleanupTranslationIDs{
		terminal:      uuid.New(),
		missing:       uuid.New(),
		active:        uuid.New(),
		unbound:       uuid.New(),
		legacyBound:   uuid.New(),
		legacyUnbound: uuid.New(),
	}
	ids.activeJobID = insertActiveRiverJob(t, pool, map[string]any{
		"translation_id": ids.active,
	}, "translate_link_v2")
	ids.legacyRiverJobID = insertActiveRiverJob(t, pool, map[string]any{
		"translation_id": ids.legacyBound,
	}, "translate_link_content")
	const missingJobID int64 = 9_000_000_000_000_000_000

	linkIDs := []uuid.UUID{uuid.New(), uuid.New(), uuid.New(), uuid.New(), uuid.New(), uuid.New()}
	if _, err := pool.Exec(t.Context(), `INSERT INTO public.links (
		id,url,source_key,status,first_collected_at
	) VALUES
		($1,'https://cleanup.example/terminal','https://cleanup.example/terminal','done',CURRENT_TIMESTAMP),
		($2,'https://cleanup.example/missing','https://cleanup.example/missing','done',CURRENT_TIMESTAMP),
		($3,'https://cleanup.example/active','https://cleanup.example/active','done',CURRENT_TIMESTAMP),
		($4,'https://cleanup.example/unbound','https://cleanup.example/unbound','done',CURRENT_TIMESTAMP),
		($5,'https://cleanup.example/legacy-bound','https://cleanup.example/legacy-bound','done',CURRENT_TIMESTAMP),
		($6,'https://cleanup.example/legacy-unbound','https://cleanup.example/legacy-unbound','done',CURRENT_TIMESTAMP)`,
		linkIDs[0], linkIDs[1], linkIDs[2], linkIDs[3], linkIDs[4], linkIDs[5]); err != nil {
		t.Fatalf("insert obsolete cleanup links: %v", err)
	}
	if _, err := pool.Exec(t.Context(), `INSERT INTO public.link_translations (
		id,link_id,scope,block_key,start_offset,end_offset,source_text,
		source_format,target_language,source_hash,source_content_revision,
		status,attempt_generation,current_river_job_id
	) VALUES
		($1,$7,'selection','content',0,6,'source','plain','zh-CN',repeat('a',64),1,'pending',1,$13),
		($2,$8,'selection','content',0,6,'source','plain','zh-CN',repeat('b',64),1,'processing',1,$14),
		($3,$9,'selection','content',0,6,'source','plain','zh-CN',repeat('c',64),1,'pending',1,$15),
		($4,$10,'selection','content',0,6,'source','plain','zh-CN',repeat('d',64),1,'pending',1,NULL),
		($5,$11,'selection','content',0,6,'source','plain','zh-CN',repeat('e',64),1,'processing',1,$16),
		($6,$12,'selection','content',0,6,'source','plain','zh-CN',repeat('f',64),1,'pending',0,NULL)`,
		ids.terminal, ids.missing, ids.active, ids.unbound, ids.legacyBound, ids.legacyUnbound,
		linkIDs[0], linkIDs[1], linkIDs[2], linkIDs[3], linkIDs[4], linkIDs[5],
		terminalJobID, missingJobID, ids.activeJobID, ids.legacyRiverJobID); err != nil {
		t.Fatalf("insert obsolete cleanup translations: %v", err)
	}
	return ids
}

func assertObsoleteCleanupTranslationStates(t *testing.T, pool migrationRowQuerier, ids obsoleteCleanupTranslationIDs) {
	t.Helper()
	var settled, active, unbound int
	if err := pool.QueryRow(t.Context(), `SELECT
		count(*) FILTER (WHERE id IN ($1,$2,$5,$6) AND status='failed'
			AND error_msg='翻译服务暂时不可用，请重试'),
		count(*) FILTER (WHERE id=$3 AND status='pending' AND error_msg IS NULL),
		count(*) FILTER (WHERE id=$4 AND status='pending' AND error_msg IS NULL)
	FROM public.link_translations
	WHERE id IN ($1,$2,$3,$4,$5,$6)`,
		ids.terminal, ids.missing, ids.active, ids.unbound, ids.legacyBound, ids.legacyUnbound).
		Scan(&settled, &active, &unbound); err != nil {
		t.Fatalf("inspect obsolete cleanup translation states: %v", err)
	}
	if settled != 4 || active != 1 || unbound != 1 {
		t.Fatalf("translation cleanup states = settled:%d active:%d unbound:%d, want 4/1/1",
			settled, active, unbound)
	}
	var legacyState string
	var legacyFinalized bool
	if err := pool.QueryRow(t.Context(), `SELECT state::text,finalized_at IS NOT NULL
		FROM public.river_job WHERE id=$1`, ids.legacyRiverJobID).Scan(&legacyState, &legacyFinalized); err != nil {
		t.Fatalf("inspect legacy translation River job: %v", err)
	}
	if legacyState != "cancelled" || !legacyFinalized {
		t.Fatalf("legacy translation River job = %s/finalized:%v, want cancelled/true",
			legacyState, legacyFinalized)
	}
}

func assertObsoleteSubsystemSchemaState(
	t *testing.T,
	pool migrationRowQuerier,
	wantTables int,
	wantColumns int,
	wantFunctions int,
) {
	t.Helper()

	var tables, columns, functions int
	if err := pool.QueryRow(t.Context(), `
		SELECT
			(SELECT count(*) FROM information_schema.tables
			 WHERE table_schema='public' AND table_name IN (
				'concept','concept_alias','concept_merge_proposal','link_concept',
				'library_classification_rules','library_review_items','reader_content_history',
				'reader_todo_projection_backfills','feed_lifecycle_repair_audit',
				'reader_tag_activity','reader_domain_activity')),
			(SELECT count(*) FROM information_schema.columns
			 WHERE table_schema='public' AND (
				(table_name='links' AND column_name IN (
					'embedding','embedding_model','library_kind_source','predicted_library_kind',
					'classification_confidence','classification_reason','classification_explanation',
					'classifier_version','requested_library_kind','requested_library_kind_source')) OR
				(table_name='sites' AND column_name IN ('needs_review','embedding','embedding_model')) OR
				(table_name='site_tags' AND column_name='concept_id'))),
			(SELECT count(*) FROM pg_proc AS proc
			 JOIN pg_namespace AS ns ON ns.oid=proc.pronamespace
			 WHERE ns.nspname='public' AND proc.proname IN (
				'reader_capture_content_history','reader_cleanup_content_history',
				'bump_concept_global_revision_update','bump_link_concept_read_revision_update'))
	`).Scan(&tables, &columns, &functions); err != nil {
		t.Fatalf("inspect obsolete subsystem schema: %v", err)
	}
	if tables != wantTables || columns != wantColumns || functions != wantFunctions {
		t.Fatalf("obsolete subsystem schema = tables:%d columns:%d functions:%d, want %d/%d/%d",
			tables, columns, functions, wantTables, wantColumns, wantFunctions)
	}
}
